import { Alert, Anchor, Box, Button, Paper, PasswordInput, Stack, Text, Title } from '@mantine/core';
import { useForm } from '@mantine/form';
import { IconAlertCircle, IconCheck, IconLock } from '@tabler/icons-react';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { resetPassword } from '../../api/auth.api';
import { AuthFrame } from '../../components/AuthFrame';

export function ResetPasswordPage() { const [params] = useSearchParams(); const token = params.get('token') ?? ''; const [success, setSuccess] = useState(false); const [error, setError] = useState<string | null>(null); const form = useForm({ initialValues: { password: '', confirmation: '' }, validate: { password: (value) => value.length >= 8 ? null : 'Use ao menos 8 caracteres.', confirmation: (value, values) => value === values.password ? null : 'As senhas não coincidem.' } }); const submit = form.onSubmit(async ({ password }) => { setError(null); try { await resetPassword({ token, password }); setSuccess(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível redefinir a senha.'); } }); return <AuthFrame><Paper className="login-card" radius="xl" p={{ base: 'xl', sm: 40 }}><Stack gap="xl"><Box><Title order={2} c="white">Nova senha</Title><Text c="dimmed" mt={6}>Defina uma nova senha para sua conta.</Text></Box>{!token && <Alert color="red">Este link de redefinição é inválido.</Alert>}{success ? <Alert color="teal" icon={<IconCheck size={18} />}>Senha atualizada. <Anchor component={Link} to="/login">Entrar agora</Anchor></Alert> : <form onSubmit={submit} noValidate><Stack gap="md"><PasswordInput disabled={!token} label="Nova senha" leftSection={<IconLock size={17} />} {...form.getInputProps('password')} /><PasswordInput disabled={!token} label="Confirmar nova senha" leftSection={<IconLock size={17} />} {...form.getInputProps('confirmation')} />{error && <Alert color="red" icon={<IconAlertCircle size={18} />}>{error}</Alert>}<Button disabled={!token} type="submit" loading={form.submitting}>Salvar nova senha</Button></Stack></form>}</Stack></Paper></AuthFrame>; }
